### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'versions(2'

### ISSUE THREAD

**Issue by asd88-a11y** [qtacore/AndroidUISpy#17]
python build.py versions(2.5.1.0)
Traceback (most recent call last):
  File "build.py", line 51, in <module>
    main(sys.argv[1])
  File "build.py", line 25, in main
    version_items[i] = int(version_items[i])
ValueError: invalid literal for int() with base 10: 'versions(2'

按指示完成指令后出现该错误。疑似int()里面的参数传入错误。不知道怎么解决

**Comment by asd88-a11y** [comment]
有可能是PYTHON版本的问题吗？

**Comment by asd88-a11y** [comment]
直接运行 UI文件夹中的 APP.py文件成功
